name: Bad CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables  
        run: |
          export API_KEY=my-super-secret-api-key
          export DB_URL=my-database-url
          export OUTPUT_DIR=/output
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Run application (without caching)  
        run: |
          pip3 install -r requirements.txt
          python3 app.py

      - name: Build Docker image 
        run: |
          docker build -t my-app .
          docker run -d -p 8080:8080 my-app

      - name: Deploy to server
        run: |
          scp -r $OUTPUT_DIR user@server:/var/www/my-app
