name: Bad

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up environment variables  
        run: |
          export API_KEY=my-super-secret-api-key
          export DB_URL=my-database-url
          export OUTPUT_DIR=/output
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
        continue-on-error: true
