version: '3.8'

services:
  web:
    image: nginx:1.21.6
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - DEBUG=true
      - API_URL=http://api:5000

  api:
    image: myapi:latest
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "your-start-command"]

  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
